const permission = [
  {
    key: "record_and_send_audio",
    name: "Record & Send Audio",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "share_photos_and_videos",
    name: "Share Photos & Videos",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "share_document",
    name: "Share Document",
    description: "Permissions to share the document",
    default: true,
    moderator: true,
    public: true,
  },
  {
    key: "start_audio_call",
    name: "Start Audio Call",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "start_video_call",
    name: "Start Video Call",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "share_contacts",
    name: "Share Contacts",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "share_location",
    name: "Share Location",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "share_poll",
    name: "Share Polls",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "allow_edit_message",
    name: "Allow to Edit Message",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
  {
    key: "create_groups",
    name: "Allow to Create Groups",
    description: "",
    default: true,
    moderator: true,
    public: false,
  },
];

export default permission;
